export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="max-w-4xl mx-auto bg-white rounded-lg shadow-sm p-8">
        <h1 className="text-4xl font-bold text-[#1E3A5F] mb-8">Terms of Service</h1>

        <p className="text-sm text-gray-500 mb-8">Last updated: {new Date().toLocaleDateString()}</p>

        <div className="prose prose-lg max-w-none space-y-6">
          <h2 className="text-2xl font-bold text-[#1E3A5F] mt-8 mb-4">1. Service Description</h2>
          <p>
            ScriptScope provides AI-powered script analysis services. Our analysis is generated entirely by artificial intelligence and is intended for educational and informational purposes only.
          </p>

          <h2 className="text-2xl font-bold text-[#1E3A5F] mt-8 mb-4">2. AI-Generated Content Disclaimer</h2>
          <p className="font-bold">IMPORTANT: READ CAREFULLY</p>

          <p>
            The analysis provided by ScriptScope is generated entirely by artificial intelligence. It is NOT a substitute for professional advice from qualified script consultants, development executives, literary agents, or entertainment attorneys.
          </p>

          <p>You acknowledge and agree that:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>AI-generated analysis may contain errors, inaccuracies, or omissions</li>
            <li>Output should not be relied upon as the sole basis for business, investment, or production decisions</li>
            <li>We make no guarantees about the accuracy, completeness, or usefulness of any analysis</li>
            <li>Results are opinions generated by AI, not professional recommendations</li>
            <li>You are solely responsible for evaluating and verifying the analysis for your purposes</li>
            <li>We do not guarantee any particular outcome from using our service</li>
          </ul>

          <h2 className="text-2xl font-bold text-[#1E3A5F] mt-8 mb-4">3. No Professional Relationship</h2>
          <p>
            Use of ScriptScope does not create any professional relationship, including but not limited to agent-client, manager-client, consultant-client, or any other advisory relationship. We do not provide professional entertainment industry advice.
          </p>

          <h2 className="text-2xl font-bold text-[#1E3A5F] mt-8 mb-4">4. Your Content & Intellectual Property</h2>
          <p>
            <strong>You retain all ownership rights to any scripts or materials you upload.</strong> ScriptScope does not claim any ownership, rights, or interest in your uploaded content.
          </p>

          <p>
            By uploading content, you grant us only a limited, temporary license to process your script solely for the purpose of providing our analysis service. This license terminates when your script is deleted from our systems.
          </p>

          <p>You represent and warrant that:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>You own or have the legal right to upload the submitted material</li>
            <li>Your submission does not infringe any third party's intellectual property or other rights</li>
            <li>You have full authority to grant the license described herein</li>
          </ul>

          <h2 className="text-2xl font-bold text-[#1E3A5F] mt-8 mb-4">5. Script Security</h2>
          <p>Your uploaded scripts are:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Encrypted in transit using TLS 1.3</li>
            <li>Encrypted at rest using AES-256 encryption</li>
            <li>Automatically deleted within 24 hours of analysis completion</li>
            <li>NEVER used to train AI models</li>
            <li>NEVER shared with, sold to, or disclosed to third parties</li>
            <li>NEVER reviewed by humans unless you specifically request technical support</li>
          </ul>

          <h2 className="text-2xl font-bold text-[#1E3A5F] mt-8 mb-4">6. Limitation of Liability</h2>
          <p className="uppercase font-bold">
            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, SCRIPTSCOPE AND ITS OPERATORS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO:
          </p>

          <ul className="list-disc pl-6 space-y-1">
            <li>Loss of profits, revenue, or business opportunities</li>
            <li>Decisions made based on our analysis</li>
            <li>Investment, financing, or production decisions influenced by our analysis</li>
            <li>Any damages arising from reliance on AI-generated content</li>
            <li>Errors, omissions, or inaccuracies in the analysis</li>
            <li>Service interruptions or technical failures</li>
          </ul>

          <p className="uppercase font-bold">
            IN NO EVENT SHALL OUR TOTAL LIABILITY FOR ANY CLAIMS ARISING FROM YOUR USE OF THE SERVICE EXCEED THE AMOUNT YOU PAID FOR THE SPECIFIC ANALYSIS IN QUESTION.
          </p>

          <p className="uppercase font-bold">
            YOU EXPRESSLY UNDERSTAND AND AGREE THAT YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK AND THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND.
          </p>

          <h2 className="text-2xl font-bold text-[#1E3A5F] mt-8 mb-4">7. Indemnification</h2>
          <p>
            You agree to indemnify, defend, and hold harmless ScriptScope and its operators, employees, and affiliates from any claims, damages, losses, or expenses (including reasonable attorneys' fees) arising from:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Your use of the service</li>
            <li>Your violation of these terms</li>
            <li>Your violation of any third party's rights</li>
            <li>Content you upload to the service</li>
            <li>Any claims that your uploaded content infringes intellectual property rights</li>
          </ul>

          <h2 className="text-2xl font-bold text-[#1E3A5F] mt-8 mb-4">8. Refunds</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>Unused credits may be refunded within 30 days of purchase</li>
            <li>Credits that have been used for analysis are non-refundable</li>
            <li>If our service fails to deliver an analysis due to technical error, you will receive a full refund or credit restoration</li>
            <li>Contact support@scriptscope.com for refund requests</li>
          </ul>

          <h2 className="text-2xl font-bold text-[#1E3A5F] mt-8 mb-4">9. Acceptable Use</h2>
          <p>You agree NOT to:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Upload content you do not have rights to</li>
            <li>Use the service for any illegal purpose</li>
            <li>Attempt to reverse engineer or extract our AI prompts or methodology</li>
            <li>Resell or redistribute our analysis without permission</li>
            <li>Use automated systems to access the service beyond normal use</li>
          </ul>

          <h2 className="text-2xl font-bold text-[#1E3A5F] mt-8 mb-4">10. Termination</h2>
          <p>
            We reserve the right to terminate or suspend your access at our discretion, without notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties.
          </p>

          <h2 className="text-2xl font-bold text-[#1E3A5F] mt-8 mb-4">11. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the laws of the State of Israel, without regard to conflict of law principles. Any disputes arising under these Terms shall be resolved exclusively in the competent courts of Tel Aviv-Jaffa, Israel.
          </p>

          <h2 className="text-2xl font-bold text-[#1E3A5F] mt-8 mb-4">12. Changes to Terms</h2>
          <p>
            We may modify these Terms at any time. We will notify you of material changes via email or notice on our site. Continued use after changes constitutes acceptance.
          </p>

          <h2 className="text-2xl font-bold text-[#1E3A5F] mt-8 mb-4">13. Severability</h2>
          <p>
            If any provision of these Terms is found unenforceable, the remaining provisions will continue in full force and effect.
          </p>

          <h2 className="text-2xl font-bold text-[#1E3A5F] mt-8 mb-4">14. Contact</h2>
          <p>Questions about these Terms: legal@scriptscope.com</p>
        </div>
      </div>
    </div>
  );
}
