import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

export async function generateAnalysisPDF(analysis: any, scriptTitle: string): Promise<Buffer> {
  try {
    const pdfDoc = await PDFDocument.create();
    const timesRoman = await pdfDoc.embedFont(StandardFonts.TimesRoman);
    const timesRomanBold = await pdfDoc.embedFont(StandardFonts.TimesRomanBold);
    const timesRomanItalic = await pdfDoc.embedFont(StandardFonts.TimesRomanItalic);

    let page = pdfDoc.addPage([612, 792]); // US Letter
    let yPosition = 750;
    const margin = 50;
    const pageWidth = 612;
    const contentWidth = pageWidth - 2 * margin;

    // Helper: clean text for PDF (preserve dashes)
    const cleanText = (text: string): string => {
      if (!text) return '';
      return String(text)
        // Replace em dashes and en dashes with spaced hyphens BEFORE stripping non-ASCII
        .replace(/—/g, ' - ') // Em dash
        .replace(/–/g, ' - ') // En dash
        .replace(/[\r\n]+/g, ' ') // Remove line breaks
        .replace(/[^\x20-\x7E]/g, '') // Strip remaining non-ASCII characters
        .replace(/\s+/g, ' ') // Normalize multiple spaces to single space
        .trim();
    };

    // Helper: wrap text
    const wrapText = (text: string, maxWidth: number, fontSize: number, font: any): string[] => {
      const words = text.split(' ');
      const lines: string[] = [];
      let currentLine = '';

      for (const word of words) {
        const testLine = currentLine + (currentLine ? ' ' : '') + word;
        const width = font.widthOfTextAtSize(testLine, fontSize);

        if (width > maxWidth && currentLine) {
          lines.push(currentLine);
          currentLine = word;
        } else {
          currentLine = testLine;
        }
      }

      if (currentLine) lines.push(currentLine);
      return lines;
    };

    const addText = (text: string, fontSize: number, font: any) => {
      const cleanedText = cleanText(text);
      const lines = wrapText(cleanedText, contentWidth, fontSize, font);
      for (const line of lines) {
        if (yPosition < 70) {
          addFooter();
          page = pdfDoc.addPage([612, 792]);
          yPosition = 750;
        }
        page.drawText(line, {
          x: margin,
          y: yPosition,
          size: fontSize,
          font: font,
          color: rgb(0, 0, 0),
        });
        yPosition -= fontSize + 4;
      }
    };

    const addHeading = (text: string, fontSize: number) => {
      yPosition -= 12;
      if (yPosition < 100) {
        addFooter();
        page = pdfDoc.addPage([612, 792]);
        yPosition = 750;
      }
      addText(text, fontSize, timesRomanBold);
      yPosition -= 8;
    };

    const addSubheading = (text: string) => {
      yPosition -= 8;
      addText(text, 11, timesRomanBold);
      yPosition -= 4;
    };

    const addBullet = (text: string) => {
      addText(`\u2022 ${text}`, 10, timesRoman);
    };

    const addReaderNote = (text: string) => {
      // Reader notes in smaller italic font with indent
      const cleanedText = cleanText(text);
      const lines = wrapText(cleanedText, contentWidth - 20, 9, timesRomanItalic);
      for (const line of lines) {
        if (yPosition < 70) {
          addFooter();
          page = pdfDoc.addPage([612, 792]);
          yPosition = 750;
        }
        page.drawText(line, {
          x: margin + 20,
          y: yPosition,
          size: 9,
          font: timesRomanItalic,
          color: rgb(0.3, 0.3, 0.3),
        });
        yPosition -= 13;
      }
    };

    const addFooter = () => {
      page.drawText(`Generated by ScriptScope | Professional Script Coverage`, {
        x: margin,
        y: 30,
        size: 8,
        font: timesRoman,
        color: rgb(0.5, 0.5, 0.5),
      });
      const pageNum = pdfDoc.getPages().indexOf(page) + 1;
      page.drawText(`Page ${pageNum}`, {
        x: pageWidth - margin - 40,
        y: 30,
        size: 8,
        font: timesRoman,
        color: rgb(0.5, 0.5, 0.5),
      });
    };

    // ========================================
    // PAGE 1: OVERVIEW
    // ========================================
    const page1 = analysis.page1_overview || {};

    yPosition = 500;
    addText('PROFESSIONAL SCRIPT COVERAGE', 20, timesRomanBold);
    yPosition -= 20;
    addText((page1.title || scriptTitle).toUpperCase(), 16, timesRomanBold);
    yPosition -= 40;
    addText(`Format: ${page1.format || 'N/A'}`, 12, timesRoman);
    addText(`Genre: ${page1.genre || 'N/A'}`, 12, timesRoman);
    addText(`Page Count: ${page1.pageCount || 'N/A'}`, 12, timesRoman);
    yPosition -= 30;

    // Grade with visual prominence
    if (page1.overallGrade) {
      addText(`GRADE: ${page1.overallGrade}`, 14, timesRomanBold);
    }
    if (page1.numericScore) {
      addText(`SCORE: ${page1.numericScore}/10`, 14, timesRomanBold);
    }
    yPosition -= 20;

    // New page for content
    page = pdfDoc.addPage([612, 792]);
    yPosition = 750;

    addHeading('LOGLINE', 14);
    addText(page1.logline || 'N/A', 10, timesRoman);
    yPosition -= 8;

    addHeading('SYNOPSIS', 14);
    addText(page1.synopsis || 'N/A', 10, timesRoman);
    yPosition -= 8;

    addHeading('EDITORIAL ASSESSMENT', 14);
    addText(page1.editorialAssessment || 'N/A', 10, timesRoman);
    yPosition -= 10;

    // Reader Notes
    if (page1.readerNotes && page1.readerNotes.length > 0) {
      addSubheading('Reader Notes:');
      page1.readerNotes.forEach((note: string) => {
        addReaderNote(`\u2022 ${note}`);
      });
      yPosition -= 5;
    }

    // ========================================
    // PAGE 2: CHARACTERS
    // ========================================
    addHeading('CHARACTER ANALYSIS', 14);

    const page2 = analysis.page2_characters || {};
    const protag = page2.protagonist || {};

    addSubheading('Protagonist');
    addText(`Name: ${protag.name || 'N/A'}`, 10, timesRomanBold);
    addText(`Goal: ${protag.goal || 'N/A'}`, 10, timesRoman);
    addText(`Flaw: ${protag.flaw || 'N/A'}`, 10, timesRoman);
    yPosition -= 5;
    addText('Arc Assessment:', 10, timesRomanBold);
    addText(protag.arcAssessment || 'N/A', 10, timesRoman);
    yPosition -= 10;

    const antag = page2.antagonist || {};
    if (antag.name && antag.name !== 'N/A') {
      addSubheading('Antagonist');
      addText(`Name: ${antag.name}`, 10, timesRomanBold);
      addText(antag.assessment || 'N/A', 10, timesRoman);
      yPosition -= 10;
    }

    addSubheading('Character List');
    const charList = page2.characterList || [];
    charList.forEach((char: any) => {
      addText(`${char.name}: ${char.function || char.description}`, 10, timesRoman);
    });
    yPosition -= 10;

    if (page2.voiceDistinction) {
      addSubheading('Voice Distinction');
      addText(page2.voiceDistinction, 10, timesRoman);
      yPosition -= 10;
    }

    addSubheading('Key Relationship Dynamics');
    addText(page2.keyDynamics || 'N/A', 10, timesRoman);
    yPosition -= 10;

    // Reader Notes
    if (page2.readerNotes && page2.readerNotes.length > 0) {
      addSubheading('Reader Notes:');
      page2.readerNotes.forEach((note: string) => {
        addReaderNote(`\u2022 ${note}`);
      });
      yPosition -= 5;
    }

    // ========================================
    // PAGE 3: STRUCTURE & STORY
    // ========================================
    addHeading('STRUCTURE & STORY', 14);

    const page3 = analysis.page3_structure || {};

    addSubheading('A Story Assessment (Main Plot)');
    addText(page3.aStoryAssessment || 'N/A', 10, timesRoman);
    yPosition -= 8;

    addSubheading('B Story Assessment');
    addText(page3.bStoryAssessment || 'N/A', 10, timesRoman);
    yPosition -= 8;

    if (page3.theme) {
      addSubheading('Theme');
      addText(page3.theme, 10, timesRoman);
      yPosition -= 8;
    }

    addSubheading('Act Breaks');
    const breaks = page3.actBreaks || {};
    if (breaks.act1End) {
      addText(`Act 1 End (Page ${breaks.act1End.page || '?'}): ${breaks.act1End.assessment || 'N/A'}`, 10, timesRoman);
    }
    if (breaks.midpoint) {
      addText(`Midpoint (Page ${breaks.midpoint.page || '?'}): ${breaks.midpoint.assessment || 'N/A'}`, 10, timesRoman);
    }
    if (breaks.act2End) {
      addText(`Act 2 End (Page ${breaks.act2End.page || '?'}): ${breaks.act2End.assessment || 'N/A'}`, 10, timesRoman);
    }
    yPosition -= 8;

    addSubheading('Pacing');
    const pacing = page3.pacing || {};
    if (pacing.dragsAt) {
      addText('Where it drags: ' + pacing.dragsAt, 10, timesRoman);
      yPosition -= 3;
    }
    if (pacing.rushesAt) {
      addText('Where it rushes: ' + pacing.rushesAt, 10, timesRoman);
      yPosition -= 3;
    }
    if (pacing.analysis) {
      addText(pacing.analysis, 10, timesRoman);
    }
    yPosition -= 8;

    addSubheading('Stakes');
    const stakes = page3.stakes || {};
    if (stakes.personal) {
      addText(`Personal: ${stakes.personal}`, 10, timesRoman);
    }
    if (stakes.external) {
      addText(`External: ${stakes.external}`, 10, timesRoman);
    }
    if (stakes.escalation) {
      addText(`Escalation: ${stakes.escalation}`, 10, timesRoman);
    }
    yPosition -= 8;

    // Reader Notes
    if (page3.readerNotes && page3.readerNotes.length > 0) {
      addSubheading('Reader Notes:');
      page3.readerNotes.forEach((note: string) => {
        addReaderNote(`\u2022 ${note}`);
      });
      yPosition -= 5;
    }

    // ========================================
    // PAGE 4: CRAFT
    // ========================================
    addHeading('CRAFT ASSESSMENT', 14);

    const page4 = analysis.page4_craft || {};

    addSubheading('Dialogue');
    const dialogue = page4.dialogue || {};
    addText(`Rating: ${dialogue.rating || 'N/A'}`, 10, timesRoman);
    addText(dialogue.assessment || 'N/A', 10, timesRoman);
    if (dialogue.bestLine) {
      yPosition -= 5;
      addText(`Best Line: "${dialogue.bestLine}"`, 10, timesRoman);
    }
    if (dialogue.weakestLine) {
      yPosition -= 5;
      addText(`Weakest Line: "${dialogue.weakestLine}"`, 10, timesRoman);
    }
    yPosition -= 10;

    addSubheading('Visual Storytelling');
    const visual = page4.visualStorytelling || {};
    addText(`Rating: ${visual.rating || 'N/A'}`, 10, timesRoman);
    addText(visual.assessment || 'N/A', 10, timesRoman);
    if (visual.bestMoment) {
      yPosition -= 5;
      addText(`Best Moment: ${visual.bestMoment}`, 10, timesRoman);
    }
    yPosition -= 10;

    addSubheading('Opening Pages');
    const opening = page4.openingPages || {};
    addText(`Hooks the reader? ${opening.hooks || 'N/A'}`, 10, timesRoman);
    addText(opening.assessment || 'N/A', 10, timesRoman);
    yPosition -= 10;

    addSubheading('Ending');
    const ending = page4.ending || {};
    addText(`Lands effectively? ${ending.lands || 'N/A'}`, 10, timesRoman);
    addText(ending.assessment || 'N/A', 10, timesRoman);
    yPosition -= 10;

    addSubheading('Originality');
    const originality = page4.originality || {};
    addText(`Score: ${originality.score || 'N/A'}/10`, 10, timesRoman);
    addText(originality.assessment || 'N/A', 10, timesRoman);
    yPosition -= 8;

    // Reader Notes
    if (page4.readerNotes && page4.readerNotes.length > 0) {
      addSubheading('Reader Notes:');
      page4.readerNotes.forEach((note: string) => {
        addReaderNote(`\u2022 ${note}`);
      });
      yPosition -= 5;
    }

    // ========================================
    // PAGE 5: DEVELOPMENT NOTES
    // ========================================
    addHeading('DEVELOPMENT NOTES', 14);

    const page5 = analysis.page5_development || {};

    addSubheading("What's Working");
    (page5.whatsWorking || []).forEach((item: string) => addBullet(item));
    yPosition -= 10;

    addSubheading('What Needs Work');
    (page5.whatNeedsWork || []).forEach((item: string) => addBullet(item));
    yPosition -= 10;

    addSubheading('Top 3 Priorities for Next Draft');
    (page5.topThreeFixes || []).forEach((item: string, idx: number) => {
      addText(`${idx + 1}. ${item}`, 10, timesRomanBold);
      yPosition -= 3;
    });
    yPosition -= 10;

    // Commercial Assessment
    const commercial = page5.commercialAssessment || {};
    if (Object.keys(commercial).length > 0) {
      addSubheading('Commercial Assessment');
      if (commercial.marketPositioning) {
        addText(`Market: ${commercial.marketPositioning}`, 10, timesRoman);
      }
      if (commercial.buyers) {
        addText(`Buyers: ${commercial.buyers}`, 10, timesRoman);
      }
      if (commercial.distribution) {
        addText(`Distribution: ${commercial.distribution}`, 10, timesRoman);
      }
      if (commercial.castability) {
        addText(`Castability: ${commercial.castability}`, 10, timesRoman);
      }
      if (commercial.budgetTier) {
        addText(`Budget: ${commercial.budgetTier}`, 10, timesRoman);
      }
      if (commercial.awardsPotential) {
        addText(`Awards: ${commercial.awardsPotential}`, 10, timesRoman);
      }
      yPosition -= 10;
    }

    if (page5.encouragement) {
      addSubheading('Encouragement');
      addText(page5.encouragement, 10, timesRoman);
    }

    addFooter();
    const pdfBytes = await pdfDoc.save();
    return Buffer.from(pdfBytes);
  } catch (error) {
    console.error('[PDF Generation] Error:', error);
    console.error('[PDF Generation] Stack:', (error as Error).stack);
    throw new Error('Failed to generate PDF');
  }
}
