import { Resend } from 'resend';

const fromEmail = 'ScriptScope <onboarding@resend.dev>';
const ownerEmail = process.env.OWNER_EMAIL || 'ariel@example.com';

// Lazy initialization to avoid errors during build
let resendClient: Resend | null = null;
function getResend() {
  if (!resendClient) {
    const apiKey = process.env.RESEND_API_KEY || '';
    resendClient = new Resend(apiKey);
  }
  return resendClient;
}

export async function sendReportReadyEmail(to: string, scriptTitle: string, reportUrl: string) {
  try {
    await getResend().emails.send({
      from: fromEmail,
      to,
      subject: `Your ScriptScope Coverage is Ready`,
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; }
            .container { max-width: 600px; margin: 0 auto; padding: 20px; }
            .header { background: linear-gradient(135deg, #0a1628 0%, #1a3a5f 100%); color: white; padding: 30px; text-align: center; border-radius: 8px 8px 0 0; }
            .content { background: white; padding: 30px; border: 1px solid #e5e7eb; border-top: none; }
            .button { background: #c9a962; color: white; padding: 14px 32px; text-decoration: none; border-radius: 8px; display: inline-block; font-weight: 600; margin: 20px 0; }
            .footer { text-align: center; padding: 20px; color: #666; font-size: 12px; }
            .script-title { color: #c9a962; font-size: 18px; font-weight: 600; margin: 10px 0; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1 style="margin: 0; font-size: 28px;">✨ Your Coverage is Ready!</h1>
            </div>
            <div class="content">
              <p style="font-size: 16px; margin-top: 0;">Great news! We've completed your professional script analysis.</p>

              <div class="script-title">${scriptTitle}</div>

              <p>Your comprehensive Emmy-winning coverage report is ready to view and download.</p>

              <div style="text-align: center;">
                <a href="${reportUrl}" class="button">View Your Report</a>
              </div>

              <p style="font-size: 14px; color: #666; margin-top: 30px;">
                <strong>What's included:</strong><br/>
                • Logline & Synopsis<br/>
                • Character Analysis<br/>
                • Story Structure Assessment<br/>
                • Commercial Viability<br/>
                • Detailed Recommendations<br/>
                • Downloadable PDF Report
              </p>
            </div>
            <div class="footer">
              <p>Analysis generated by AI • For informational purposes only</p>
              <p>© ${new Date().getFullYear()} ScriptScope. All rights reserved.</p>
            </div>
          </div>
        </body>
        </html>
      `,
    });
  } catch (error) {
    console.error('Failed to send report ready email:', error);
  }
}

export async function sendPurchaseConfirmationEmail(to: string, credits: number) {
  try {
    await getResend().emails.send({
      from: fromEmail,
      to,
      subject: 'Thank you for your purchase - ScriptScope',
      html: `
        <h1>Purchase confirmed!</h1>
        <p>You now have <strong>${credits} credit${credits > 1 ? 's' : ''}</strong> available.</p>
        <p><a href="${process.env.NEXT_PUBLIC_APP_URL}/analyze" style="background: #1E3A5F; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">Analyze a Script</a></p>
      `,
    });
  } catch (error) {
    console.error('Failed to send purchase confirmation email:', error);
  }
}

export async function sendAnalysisFailedEmail(to: string, scriptTitle: string) {
  try {
    await getResend().emails.send({
      from: fromEmail,
      to,
      subject: 'Issue with Your Script Analysis - ScriptScope',
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; }
            .container { max-width: 600px; margin: 0 auto; padding: 20px; }
            .header { background: #dc2626; color: white; padding: 30px; text-align: center; border-radius: 8px 8px 0 0; }
            .content { background: white; padding: 30px; border: 1px solid #e5e7eb; border-top: none; }
            .button { background: #c9a962; color: white; padding: 14px 32px; text-decoration: none; border-radius: 8px; display: inline-block; font-weight: 600; margin: 20px 0; }
            .footer { text-align: center; padding: 20px; color: #666; font-size: 12px; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1 style="margin: 0; font-size: 24px;">We're Looking Into It</h1>
            </div>
            <div class="content">
              <p style="font-size: 16px; margin-top: 0;">We encountered an issue while analyzing "${scriptTitle}".</p>

              <p><strong>We've automatically refunded your credit.</strong></p>

              <p>Our team has been notified and we're investigating the issue. This is rare and we apologize for the inconvenience.</p>

              <p>Please try again, and if the issue persists, reply to this email and we'll personally assist you.</p>

              <div style="text-align: center;">
                <a href="${process.env.NEXT_PUBLIC_APP_URL}/analyze" class="button">Try Again</a>
              </div>
            </div>
            <div class="footer">
              <p>© ${new Date().getFullYear()} ScriptScope. All rights reserved.</p>
            </div>
          </div>
        </body>
        </html>
      `,
    });
  } catch (error) {
    console.error('Failed to send analysis failed email:', error);
  }
}

export async function sendRefundIssuedEmail(to: string, credits: number) {
  try {
    await getResend().emails.send({
      from: fromEmail,
      to,
      subject: 'Refund issued - ScriptScope',
      html: `
        <h1>Refund Issued</h1>
        <p>We apologize for the inconvenience. We've restored <strong>${credits} credit${credits > 1 ? 's' : ''}</strong> to your account.</p>
        <p>If you have any questions, please reply to this email.</p>
      `,
    });
  } catch (error) {
    console.error('Failed to send refund email:', error);
  }
}

export async function sendDailyDigestEmail(stats: {
  date: string;
  revenue: number;
  scripts_analyzed: number;
  signups: number;
  refunds: number;
  issues: string[];
}) {
  try {
    await getResend().emails.send({
      from: fromEmail,
      to: ownerEmail,
      subject: `ScriptScope Daily Digest - ${stats.date}`,
      html: `
        <h1>Daily Digest - ${stats.date}</h1>

        <h2>Revenue</h2>
        <p style="font-size: 24px; font-weight: bold;">$${stats.revenue.toFixed(2)}</p>

        <h2>Activity</h2>
        <ul>
          <li><strong>${stats.scripts_analyzed}</strong> scripts analyzed</li>
          <li><strong>${stats.signups}</strong> new signups</li>
          <li><strong>${stats.refunds}</strong> refunds issued</li>
        </ul>

        ${stats.issues.length > 0 ? `
          <h2>⚠️ Issues</h2>
          <ul>
            ${stats.issues.map(issue => `<li>${issue}</li>`).join('')}
          </ul>
        ` : '<p>✅ No issues to report</p>'}
      `,
    });
  } catch (error) {
    console.error('Failed to send daily digest email:', error);
  }
}

export async function sendContactEmail(name: string, email: string, message: string) {
  try {
    await getResend().emails.send({
      from: fromEmail,
      to: ownerEmail,
      replyTo: email,
      subject: `ScriptScope Contact Form: ${name}`,
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; }
            .container { max-width: 600px; margin: 0 auto; padding: 20px; }
            .header { background: linear-gradient(135deg, #0a1628 0%, #1a3a5f 100%); color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0; }
            .content { background: white; padding: 30px; border: 1px solid #e5e7eb; border-top: none; }
            .info { background: #f3f4f6; padding: 15px; border-radius: 6px; margin-bottom: 20px; }
            .message { background: #f9fafb; padding: 20px; border-left: 4px solid #c9a962; border-radius: 4px; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1 style="margin: 0; font-size: 20px;">📧 Contact Form Submission</h1>
            </div>
            <div class="content">
              <div class="info">
                <p style="margin: 0 0 10px 0;"><strong>From:</strong> ${name}</p>
                <p style="margin: 0;"><strong>Email:</strong> <a href="mailto:${email}">${email}</a></p>
              </div>

              <h2 style="color: #0a1628; margin-top: 20px;">Message:</h2>
              <div class="message">
                <p style="margin: 0; white-space: pre-wrap;">${message}</p>
              </div>

              <p style="margin-top: 30px; font-size: 14px; color: #666;">
                Reply directly to this email to respond to ${name}.
              </p>
            </div>
          </div>
        </body>
        </html>
      `,
    });
  } catch (error) {
    console.error('Failed to send contact email:', error);
    throw error;
  }
}
